version: '3.9'

services:
  synclounge:
    container_name: synclounge
    image: lscr.io/linuxserver/synclounge:latest
    environment:
      - AUTH_LIST=plexuser1,plexuser2,email1,machineid1 #optional
      - AUTOJOIN_ENABLED=false #optional
      - AUTOJOIN_ROOM=roomname #optional
    ports:
      - 8088:8088
    restart: unless-stopped